apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: fraud
spec:
  containers:
    - name: task-pv-container
      image: nginx # https://www.nginx.com/
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
#      gcePersistentDisk:
#        pdName:
#      awsElasticBlockStore:
#        volumeID: