apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fraud-deployment
  labels:
    app: fraud
  namespace: fraud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - image:  worldbosskafka/fraud:1.0.2
          name:  fraud
          resources:
            limits:
              cpu: "1Gi"
              memory: "1Gi"
            requests:
              cpu: "0.5Gi"
              memory: "500Mi"
          ports:
            - containerPort:  23321

